version: '3'
services:
  storykeeper-nginx:
    container_name: "storykeeper-nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - storykeeper-app
    ports:
      - 80:80
    volumes:
      - ./:/src

  storykeeper-app:
    container_name: "storykeeper-app"
    build:
      context: ./docker/php
    depends_on:
      - storykeeper-mysql
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini

    postgres:
        image: postgres:14.5-bullseye
        container_name: my_postgres
        ports:
          - "5432:5432"
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        volumes:
          - ./data:/var/lib/postgresql/data
          - ./init:/docker-entrypoint-initdb.d